name: 'Flipt Validate Action'
description: 'Run Flipt Validate for features.yaml files'
author: 'Flipt Devs <dev@flipt.io>'
inputs:
  args:
    description: 'additional arguments to pass to the command'
    default: ''
    required: false
  working-directory:
    description: 'working directory, default is project root'
    required: false
  github-token:
    required: false
    description: 'GitHub Token for downloading artifacts'
runs:
  using: 'node16'
  main: 'dist/index.js'
